create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  contact text not null,
  subject text not null,
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  name text,
  email text,
  feedback_type text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.contact_messages enable row level security;
alter table public.feedback enable row level security;
